/** Extension lifecycle events emitted by the Spindle system */
export enum SpindleEvent {
  EXTENSION_LOADED = "EXTENSION_LOADED",
  EXTENSION_UNLOADED = "EXTENSION_UNLOADED",
  EXTENSION_ERROR = "EXTENSION_ERROR",
  PERMISSION_CHANGED = "PERMISSION_CHANGED",
}

/**
 * Core Lumiverse event types that extensions can subscribe to.
 * Mirrors the backend EventType enum.
 */
export enum CoreEventType {
  CONNECTED = "CONNECTED",
  CHAT_CHANGED = "CHAT_CHANGED",
  MESSAGE_SENT = "MESSAGE_SENT",
  MESSAGE_EDITED = "MESSAGE_EDITED",
  MESSAGE_DELETED = "MESSAGE_DELETED",
  MESSAGE_SWIPED = "MESSAGE_SWIPED",
  CHARACTER_MESSAGE_RENDERED = "CHARACTER_MESSAGE_RENDERED",
  USER_MESSAGE_RENDERED = "USER_MESSAGE_RENDERED",
  GENERATION_STARTED = "GENERATION_STARTED",
  GENERATION_ENDED = "GENERATION_ENDED",
  GENERATION_STOPPED = "GENERATION_STOPPED",
  STREAM_TOKEN_RECEIVED = "STREAM_TOKEN_RECEIVED",
  CHARACTER_EDITED = "CHARACTER_EDITED",
  CHARACTER_DELETED = "CHARACTER_DELETED",
  CHARACTER_DUPLICATED = "CHARACTER_DUPLICATED",
  PERSONA_CHANGED = "PERSONA_CHANGED",
  IMAGE_UPLOADED = "IMAGE_UPLOADED",
  IMAGE_DELETED = "IMAGE_DELETED",
  SETTINGS_UPDATED = "SETTINGS_UPDATED",
  PRESET_CHANGED = "PRESET_CHANGED",
  CONNECTION_PROFILE_LOADED = "CONNECTION_PROFILE_LOADED",
  MAIN_API_CHANGED = "MAIN_API_CHANGED",
  WORLD_INFO_ACTIVATED = "WORLD_INFO_ACTIVATED",
  MESSAGE_TAG_INTERCEPTED = "MESSAGE_TAG_INTERCEPTED",
  TOOL_INVOCATION = "TOOL_INVOCATION",
}
