export type {
  SpindleManifest,
  SpindlePermission,
  SpindleCapability,
} from "./manifest";
export {
  IDENTIFIER_PATTERN,
  validateIdentifier,
} from "./manifest";

export type { SpindlePermission as SpindlePermissionType } from "./permissions";
export { ALL_PERMISSIONS, isValidPermission } from "./permissions";

export type { SpindleCapability as SpindleCapabilityType } from "./capabilities";
export { ALL_CAPABILITIES, isValidCapability } from "./capabilities";

export { SpindleEvent, CoreEventType } from "./events";

export type {
  LlmMessageDTO,
  SpindleUserRoleDTO,
  InterceptorBreakdownEntryDTO,
  InterceptorResultDTO,
  MacroDefinitionDTO,
  MacroInvocationContextDTO,
  MacroResolveOptionsDTO,
  MacroResolveResultDTO,
  ToolRegistrationDTO,
  ToolSchemaDTO,
  ToolCallDTO,
  GenerationRequestDTO,
  GenerationReasoningOverrideDTO,
  ReasoningEffortDTO,
  ReasoningSettingsDTO,
  ThinkingDisplayDTO,
  ConnectionReasoningBindingsDTO,
  ChatAppendGenerationOptionsDTO,
  ChatAppendMessageOptionsDTO,
  StreamChunkDTO,
  RequestInitDTO,
  ConnectionProfileDTO,
  PermissionDeniedDetail,
  PermissionChangedDetail,
  CharacterDTO,
  CharacterCreateDTO,
  CharacterAvatarUploadDTO,
  CharacterUpdateDTO,
    ChatDTO,
    ChatUpdateDTO,
    ChatSwitchedPayloadDTO,
    ChatChangedPayloadDTO,
    ChatForkedPayloadDTO,
    PromptVariableOptionDTO,
    PromptVariableDefDTO,
    PromptVariableTypeDTO,
    PromptVariableValueDTO,
    PromptVariableValuesDTO,
    PromptBlockRoleDTO,
    PromptBlockPositionDTO,
    PromptBlockCategoryModeDTO,
    PromptBlockDTO,
    PromptBlockCreateDTO,
    PromptBlockUpdateDTO,
    PromptBlockCategoryGroupDTO,
    UserPresetDTO,
    UserPresetCreateDTO,
    UserPresetUpdateDTO,
    WorldBookDTO,
  WorldBookCreateDTO,
  WorldBookUpdateDTO,
  WorldBookEntryDTO,
  WorldBookEntryCreateDTO,
  WorldBookEntryUpdateDTO,
  RegexPlacementDTO,
  RegexScopeDTO,
  RegexTargetDTO,
  RegexMacroModeDTO,
  RegexScriptDTO,
  RegexScriptCreateDTO,
  RegexScriptUpdateDTO,
  RegexScriptListOptionsDTO,
  RegexScriptActiveOptionsDTO,
  WorldInfoInterceptorEntryDTO,
  WorldInfoInterceptorMessageDTO,
  WorldInfoInterceptorCtxDTO,
  WorldInfoInterceptorMutationDTO,
  WorldInfoInterceptorResultDTO,
  DatabankScopeDTO,
  DatabankDocumentStatusDTO,
  DatabankDTO,
  DatabankCreateDTO,
  DatabankUpdateDTO,
  DatabankDocumentDTO,
  DatabankDocumentCreateDTO,
  DatabankDocumentUpdateDTO,
  PersonaDTO,
  LumiaItemDTO,
  PersonaCreateDTO,
  PersonaUpdateDTO,
  ActivatedWorldInfoEntryDTO,
  DryRunRequestDTO,
  DryRunResultDTO,
  AssemblyBreakdownEntryDTO,
  ActivationStatsDTO,
  MemoryStatsDTO,
  DryRunTokenCountDTO,
  ChatMemoryChunkDTO,
  ChatMemoryResultDTO,
   ImageGenConnectionDTO,
   ImageGenParameterSchemaDTO,
    ImageGenProviderDTO,
    ImageGenRequestDTO,
    ImageGenResultDTO,
    ImageGetOptionsDTO,
    ImageDTO,
    ImageListOptionsDTO,
    ImageSpecificityDTO,
    ImageUploadDTO,
    ImageUploadFromDataUrlOptionsDTO,
    ThemeOverrideDTO,
  ThemeInfoDTO,
  ThemePaletteConfigDTO,
  ThemeVariablesConfigDTO,
  ColorExtractionResult,
  ColorRGB,
  ColorHSL,
  SpindleModalItemDTO,
   SpindleCommandDTO,
   SpindleCommandContextDTO,
   SpindleUIDrawerTabDTO,
   SpindleUISettingsTabDTO,
   FrontendProcessStateDTO,
   FrontendProcessExitReasonDTO,
   FrontendProcessSpawnOptionsDTO,
   FrontendProcessListOptionsDTO,
   FrontendProcessInfoDTO,
   FrontendProcessLifecycleEventDTO,
   FrontendProcessStopOptionsDTO,
   BackendProcessStateDTO,
   BackendProcessExitReasonDTO,
   BackendProcessSpawnOptionsDTO,
   BackendProcessListOptionsDTO,
   BackendProcessInfoDTO,
   BackendProcessLifecycleEventDTO,
   BackendProcessStopOptionsDTO,
    GenerationStartedPayloadDTO,
  StreamTokenPayloadDTO,
  GenerationEndedPayloadDTO,
  GenerationStoppedPayloadDTO,
  GenerationObserver,
  ChatMessageDTO,
  MessageSwipeAction,
  MessageSwipedPayloadDTO,
  SwipeEditedPayloadDTO,
  ToolInvocationPayloadDTO,
  TokenModelSourceDTO,
  TokenCountOptionsDTO,
  TokenCountResultDTO,
  SharedRpcRequestContextDTO,
  SharedRpcEndpointPolicyDTO,
  MacroInterceptorPhase,
  MacroInterceptorEnvDTO,
  MacroInterceptorCtxDTO,
  MacroInterceptorResultDTO,
  MacroInterceptorRichResultDTO,
  MessageContentProcessorOrigin,
  MessageContentProcessorCtxDTO,
  MessageContentProcessorResultDTO,
  WebSearchProviderDTO,
  WebSearchSettingsDTO,
  WebSearchResultDTO,
  WebSearchDocumentDTO,
  WebSearchRequestDTO,
  WebSearchResponseDTO,
  WorkerToHost,
  HostToWorker,
} from "./api";
export { PERMISSION_DENIED_PREFIX } from "./api";

export type { ToolRegistration, JSONSchema } from "./tools";

export type {
  SpindleDOMHelper,
  SpindleMountPoint,
  SpindleUploadFile,
    SpindleMessageTagIntercept,
    SpindleMessageTagInterceptorOptions,
    SpindleMessageWidgetOptions,
    PermissionRequestOptions,
  SpindleFrontendContext,
  SpindleFrontendModule,
  SpindleDrawerTabOptions,
  SpindleDrawerTabHandle,
  SpindleFloatWidgetOptions,
  SpindleFloatWidgetHandle,
  SpindleDockEdge,
  SpindleDockPanelOptions,
  SpindleDockPanelHandle,
  SpindleAppMountOptions,
  SpindleAppMountHandle,
   SpindleInputBarActionOptions,
   SpindleInputBarActionHandle,
    SpindleSandboxFrameOptions,
    SpindleSandboxFrameHandle,
    SpindleSandboxMediaResource,
    SpindleSandboxAudioOptions,
    SpindleSandboxAudioHandle,
    SpindleSandboxAPI,
   SpindleContextMenuOptions,
   SpindleContextMenuItemDef,
   SpindleContextMenuResult,
  SpindleModalOptions,
  SpindleModalHandle,
   SpindleConfirmVariant,
    SpindleConfirmOptions,
    SpindleConfirmResult,
    SpindleUIDomActionEventType,
    SpindleUIKeyboardState,
    SpindleUIDrawerState,
    SpindleUISettingsState,
    SpindleUIDomActionDetail,
    SpindleUIDomActionBindingOptions,
    SpindleUIEventsHelper,
    SpindleFrontendProcessContext,
    SpindleFrontendProcessRegistry,
    SpindleDisplayResolver,
    SpindleDisplayResolverRegistry,
    SpindleDisplayContext,
    SpindleDisplayBodyArgs,
    SpindleDisplayTemplatesArgs,
    SpindleDisplayScriptsArgs,
    SpindleDisplayResolveResult,
    SpindleDisplayTemplatesResult,
    SpindleTabLocation,
  } from "./dom";

export type {
  SpindleMountedComponent,
  SpindleComponentTarget,
  SpindleConnectionKind,
  SpindleConnectionRef,
  SpindleTextInputOptions,
  SpindleTextInputHandle,
  SpindleTextAreaOptions,
  SpindleTextAreaHandle,
  SpindleNumericInputOptions,
  SpindleNumericInputHandle,
  SpindleNumberStepperOptions,
  SpindleNumberStepperHandle,
  SpindleRangeSliderFormat,
  SpindleRangeSliderOptions,
  SpindleRangeSliderHandle,
  SpindleCheckboxOptions,
  SpindleCheckboxHandle,
  SpindleSwitchOptions,
  SpindleSwitchHandle,
  SpindleSelectOption,
  SpindleSelectOptionLeading,
  SpindleSelectOptionsBase,
  SpindleSelectOptions,
  SpindleSelectHandle,
  SpindleMultiSelectOptions,
  SpindleMultiSelectHandle,
  SpindleModelComboboxOptions,
  SpindleModelComboboxHandle,
  SpindleFolderDropdownOptions,
  SpindleFolderDropdownHandle,
  SpindleBadgeColor,
  SpindleBadgeOptions,
  SpindleBadgeHandle,
  SpindleSpinnerOptions,
  SpindleSpinnerHandle,
  SpindleCollapsibleSectionOptions,
  SpindleCollapsibleSectionHandle,
  SpindlePaginationOptions,
  SpindlePaginationHandle,
  SpindleCloseButtonOptions,
  SpindleCloseButtonHandle,
  SpindleComponentsHelper,
} from "./components";

export type { ExtensionInfo } from "./extension-info";

export type {
  EntityTypeDTO,
  EntityStatusDTO,
  MentionRoleDTO,
  RelationTypeDTO,
  RelationStatusDTO,
  EmotionalTagDTO,
  NarrativeFlagDTO,
  ContradictionFlagDTO,
  FactExtractionStatusDTO,
  EntityConfidenceDTO,
  SalienceSourceDTO,
  ChatLinkTypeDTO,
  SalienceBreakdownDTO,
  MemoryEntityDTO,
  MemoryEntityUpsertDTO,
  MemoryEntityStatusUpdateDTO,
  MemoryMentionDTO,
  MemoryRelationDTO,
  MemoryRelationUpsertDTO,
  StatusChangeDTO,
  MemorySalienceDTO,
  MemoryConsolidationDTO,
  CortexQueryDTO,
  CortexMemoryComponentsDTO,
  CortexMemoryDTO,
  EntitySnapshotRelationshipDTO,
  EntitySnapshotDTO,
  RelationEdgeDTO,
  CortexStatsDTO,
  CortexResultDTO,
  VaultDTO,
  VaultChunkDTO,
  VaultEntityDTO,
  VaultRelationDTO,
  VaultCreateDTO,
  VaultWithContentsDTO,
  VaultReindexResultDTO,
  ChatLinkDTO,
  ChatLinkAttachDTO,
  VaultCortexDataDTO,
  InterlinkCortexDataDTO,
  LinkedCortexResultDTO,
  MemoryCortexConfigDTO,
  CortexUsageStatsDTO,
  CortexIngestionTimingsDTO,
  CortexIngestionStatusDTO,
  CortexIngestionTelemetryDTO,
  ChatChunkDTO,
  ChatMemoryWarmupResultDTO,
} from "./memories";

export type {
  SpindleAPI,
  SpindlePromptRegex,
  FrontendProcessHandle,
  BackendProcessHandle,
  SpindleBackendProcessContext,
  SpindleBackendProcessModule,
} from "./spindle-api";

export type {
  CouncilMember,
  CouncilMemberContext,
  SidecarConfig,
  CouncilSidecarConfig,
  CouncilToolsSettings,
  CouncilSettings,
  CouncilToolResult,
  CouncilExecutionResult,
  CachedCouncilResult,
  CouncilToolCategory,
  CouncilToolExecution,
  CouncilToolDefinition,
} from "./council";
export {
  SIDECAR_DEFAULTS,
  COUNCIL_SIDECAR_DEFAULTS,
  COUNCIL_TOOLS_DEFAULTS,
  COUNCIL_SETTINGS_DEFAULTS,
} from "./council";
